[server]
headless = true

[theme]
primaryColor="#F63366"            # ボタンとかの色
backgroundColor="#d7edc5"         # メイン背景色
secondaryBackgroundColor="#dcd9fa" # サイドバーやカードの色
textColor="#252129"               # 文字色
font="sans serif"                 # "sans serif" / "serif" / "monospace"
